name: luffy
channels:
  - conda-forge
  - http://data-source-conda.sankuai.com/cloud/conda-forge
  - http://data-source-conda.sankuai.com/cloud/pytorch/
  - http://data-source-conda.sankuai.com/cloud/menpo/
  - http://data-source-conda.sankuai.com/cloud/conda-forge/
  - http://data-source-conda.sankuai.com/pkgs/free/
  - http://data-source-conda.sankuai.com/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.6.0=h26f9b46_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - airports-py==1.0.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - bitsandbytes==0.42.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.0
      - codetiming==1.4.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - compressed-tensors==0.8.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataproperty==1.1.0
      - datasets==3.2.0
      - debugpy==1.8.17
      - deepspeed==0.15.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - filelock==3.16.1
      - fire==0.7.0
      - flash-attn==2.7.3
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-aiplatform==1.79.0
      - google-cloud-bigquery==3.29.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - h11==0.14.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - interegular==0.3.3
      - isort==5.13.2
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - latex2sympy2-extended==1.0.9
      - lightning-utilities==0.11.9
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - loralib==0.1.2
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - math-verify==0.6.0
      - matplotlib==3.10.1
      - mbstrdecoder==1.1.4
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - mistral-common==1.5.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numba==0.60.0
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.6.0
      - omegaconf==2.3.0
      - openai==1.59.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - optimum==1.23.3
      - orjson==3.10.15
      - outlines==0.0.46
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - pathvalidate==3.2.3
      - peft==0.14.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==3.1.1
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyairports==0.0.1
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygments==2.19.0
      - pylatexenc==2.10
      - pyparsing==3.2.1
      - pytablewriter==1.2.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - ray==2.49.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rouge-score==0.1.2
      - rpds-py==0.22.3
      - rsa==4.9
      - sacrebleu==2.5.1
      - safetensors==0.5.0
      - scikit-learn==1.6.1
      - scipy==1.15.0
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - starlette==0.41.3
      - sympy==1.13.3
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.5.0
      - termcolor==2.5.0
      - textual==1.0.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timeout-decorator==0.5.0
      - tokenizers==0.21.4
      - tomli==2.2.1
      - torch==2.4.0
      - torchmetrics==1.6.1
      - torchvision==0.19.0
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.55.4
      - transformers-stream-generator==0.0.5
      - triton==3.0.0
      - typepy==1.3.4
      - typer-slim==0.15.3
      - typing-extensions==4.12.2
      - typing-inspection==0.4.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - verl==0.1
      - virtualenv==20.28.1
      - vllm==0.6.3
      - wandb==0.19.1
      - watchfiles==1.0.3
      - websockets==14.1
      - werkzeug==3.1.3
      - word2number==1.1
      - wrapt==1.17.0
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
prefix: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/liuxinyu67/miniconda/envs/luffy
